
analyzer:
  errors:
    must_be_immutable: ignore
    non_constant_identifier_names: ignore
    unnecessary_lambdas: ignore
    use_build_context_synchronously: ignore


include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_typing_uninitialized_variables
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - avoid_unused_constructor_parameters
    - unnecessary_lambdas
