name: elevante
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  # Netowrking
  get_it: ^7.6.7
  pretty_dio_logger: ^1.4.0
  dio: ^5.5.0
  http_parser: ^4.0.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  # UI
  lottie: ^3.1.2
  cached_network_image: ^3.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
